### ISSUE TITLE
Subscriptions are only working sporadically

### ISSUE THREAD

**Issue by stefanoTron** [prismagraphql/graphcool-framework#557]
**Current behavior**
Sometimes subscriptions work, sometimes they don't. There is no precise pattern. Our code has not changed in weeks, nor have our dependencies.

**Reproduction**
Setup real-time subscriptions with Apollo (I'm using `apollo-client 2.3.2`), or use the Playground. Observe how sometimes nothing happens on a CREATE or a UPDATE  mutation.

**Expected behavior?**
When creating/updating a subscribed node, it should trigger a CREATE or UPDATE mutation, everytime in realtime.

Thanks

**Comment by marktani** [comment]
Thanks. Can you prepare a minimal setup for which you confirmed this to happen?

**Comment by littletower** [comment]
1) In the console create a type like this:
```graphql
type Post @model {
  id: ID! @isUnique
  title: String!
}
```

2) Manually, in the console, create to `Posts`, with as title `Title1` and `Title2`

3) Then in the playground type this:
```graphql
subscription updatePost {
  Post(
    filter: {
      mutation_in: [UPDATED]
    }
  ) {
    mutation
    node {
      title
    }
  }
}
```

4) Now go and change `Title1` to `foo`

5) Observe in the playground if anything happened. Sometimes it does, sometime it doesn't, you might have to change the `title` multiple times before the issue occurs. In that case you have to repeat step 
4, but instead of `foo` another value like `foo2`and so forth.

**Comment by littletower** [comment]
@marktani @dpetrick @nikolasburk @schickling this issue is still happening, is there anything we can do to help?

**Comment by dpetrick** [comment]
I'm investigating the issue and I'll try a few fixes over the next hour.

**Comment by littletower** [comment]
thanks, let's hope it does not
